webtalk_init -webtalk_dir H:/ESE465/FIR_Peripheral/FIR_Peripheral.sim/sim_1/behav/xsim/xsim.dir/Axi4FIR_Periph_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 11 18:17:24 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210641303_1777494432_210710718_223" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "af4568a1-d43d-44a5-a0ee-bcd70c4a6165" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2181cb4d5c6948f5ae63e9c9992a47ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "139" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "501 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.39_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14804_KB" -context "xsim\\usage"
webtalk_transmit -clientid 60628117 -regid "210641303_1777494432_210710718_223" -xml H:/ESE465/FIR_Peripheral/FIR_Peripheral.sim/sim_1/behav/xsim/xsim.dir/Axi4FIR_Periph_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/ESE465/FIR_Peripheral/FIR_Peripheral.sim/sim_1/behav/xsim/xsim.dir/Axi4FIR_Periph_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/ESE465/FIR_Peripheral/FIR_Peripheral.sim/sim_1/behav/xsim/xsim.dir/Axi4FIR_Periph_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
